//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyConverter
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyExchangeRate
    {
        public int Id { get; set; }
        public string Currency { get; set; }
        public double RateInINR { get; set; }
        public System.DateTime RowUpdatedDate { get; set; }
    }
}
